# Fibonacci Sequence Closed Form

The Fibonacci sequence is defined as follows:
- $F(0) = 0$
- $F(1) = 1$
- $F(n) = F(n-1) + F(n-2)$ for $n \geq 2$

As we all know, the closed form of the Fibonacci sequence is given by the Binet's formula:
$$F(n) = \frac{\phi^n - \psi^n}{\sqrt{5}}$$
where $\phi = \frac{1 + \sqrt{5}}{2}$ and $\psi = \frac{1 - \sqrt{5}}{2}$.

And $\phi$ is called the golden ratio, which is approximately equal to $1.61803398875$.

But in this notebook, we are going to derive the closed form of the Fibonacci sequence using the Matrix Exponentiation technique.


## Matrix Exponentiation

Matrix Exponentiation is a technique used to calculate the power of a matrix in $O(\log n)$ time complexity. The idea is to represent the Fibonacci sequence in the form of a matrix and then calculate the power of the matrix to get the $n^{th}$ Fibonacci number.


### Fibonacci Matrix

The Fibonacci sequence can be represented in the form of a matrix as follows:

$$
\begin{bmatrix}
F(n) \\
F(n + 1)
\end{bmatrix}
=
\begin{bmatrix}
0 & 1 \\
1 & 1  
\end{bmatrix}
\begin{bmatrix}
F(n) \\
F(n - 1)
\end{bmatrix}
$$

let matrix $A$ be:

$$
A =
\begin{bmatrix}
0 & 1 \\
1 & 1
\end{bmatrix}
$$

Fortunately, the matrix $A$ is a symmetric matrix, and its eigenvalues are $\phi$ and $\psi$. Thus, the matrix $A$ can be diagonalized as follows:

$$
A = P \Lambda P^{-1}
$$

where $P$ is the matrix of eigenvectors and $\Lambda$ is the diagonal matrix of eigenvalues.

$$
P = 
\begin{bmatrix}
\phi & \psi \\
1 & 1
\end{bmatrix},
$$
and 
$$
D =
\begin{bmatrix}
\phi & 0 \\
0 & \psi
\end{bmatrix}
$$

Thus, the n+1 Fibonacci number can be calculated as follows:

$$

\begin{bmatrix}
F(n) \\
F(n + 1)
\end{bmatrix}
=
P\Lambda^{n}P^{-1}
\begin{bmatrix}
F(0) \\
F(1)
\end{bmatrix}
$$

Expanding the above equation, we get:

$$
\begin{bmatrix}
F(n) \\
F(n + 1)
\end{bmatrix}

=
\begin{bmatrix}
\phi & \psi \\
1 & 1
\end{bmatrix}
\begin{bmatrix}
\phi^n & 0 \\
0 & \psi^n
\end{bmatrix}
\begin{bmatrix}
1 & -\psi \\
-1 & \phi
\end{bmatrix}
\begin{bmatrix}
0 \\
1
\end{bmatrix}
$$
, collecting the terms, we get:

$$
\begin{bmatrix}
F(n) \\
F(n + 1)
\end{bmatrix}
=

\frac{
\begin{bmatrix}
\phi^{n-1} - \psi^{n-1} & \phi^{n} - \psi^{n}  \\
\phi^{n} - \psi^{n} & \phi^{n + 1} - \psi^{n+1}
\end{bmatrix}}
{\sqrt{5}}
\begin{bmatrix}
0 \\
1
\end{bmatrix}
$$

Thus, the $n^{th}$ Fibonacci number can be calculated as follows:

$$
F(n) = \frac{\phi^n - \psi^n}{\sqrt{5}}
$$

In [18]:
import numpy as np

A = np.matrix([[0, 1], [1, 1]])

# A can be diagonalized

print(A)

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

# A = PDP^-1

P = eigenvectors
D = np.diag(eigenvalues)

print(P)
print(D)

# let n = 100

A_n = P @ np.linalg.matrix_power(D, 100) @ np.linalg.inv(P)

print(A_n)

# len f_n = A_n @ f_0, f_0 = [1, 0]

f_0 = np.matrix([[0], [1]])

f_n = A_n @ f_0

res = f_n[0, 0] # get the (0, 0) element of the matrix

print("Fibonacci number at n = 100 is", res)


[[0 1]
 [1 1]]
[-0.61803399  1.61803399]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
[[-0.61803399  0.        ]
 [ 0.          1.61803399]]
[[2.18922996e+20 3.54224848e+20]
 [3.54224848e+20 5.73147844e+20]]
Fibonacci number at n = 100 is 3.542248481792618e+20


In [13]:
def fib(n):
    return (1 / np.sqrt(5)) * (((1 + np.sqrt(5)) / 2)**n - ((1 - np.sqrt(5)) / 2)**n)

res2 = fib(100)

print("Fibonacci number at n = 100 is", res2)

Fibonacci number at n = 100 is 3.542248481792631e+20
